adding macos alias block to sub scripts

diff --git a/analyze b/analyze
--- a/analyze
+++ b/analyze
@@ -13,6 +13,18 @@
 #enter safe-mode (no more undefined variables!)
 set -eu -o pipefail
 
+# cross-OS compatibility (greadlink, gsed, gzcat are GNU implementations for OS X)
+[[ $(uname) == 'Darwin' ]] && {
+    shopt -s expand_aliases
+    which greadlink gsed gzcat gjoin gmktemp > /dev/null && {
+        unalias readlink sed zcat join mktemp
+        alias readlink=greadlink sed=gsed zcat=gzcat join=gjoin mktemp=gmktemp
+    } || {
+        echo 'ERROR: GNU utils required for Mac. You may use homebrew to install them: brew install coreutils gnu-sed'
+        exit 1
+    }
+}
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 echo "performing timespan analysis $SPAN_DAYS days since $EARLIEST_PR" > /dev/stderr
